### ISSUE TITLE
All objects selected

### ISSUE THREAD

**Issue by rmoliveira-etux** [bheisig/rt-extension-referenceidoitobjects#4]
Hi,
 We have a 4.4 RT installation, integrated with an 1.12.2 installation of i-doit. We've seen a strange behaviour after migrating to this i-doit version: the object selection list which shows up on RT's "References i-doit objects" view always shows all objects selected.

 We currently have a 20+ tenant installation (multi-tenant plugin) and at least one of them has almost 2k items registered on the database. Having to manually deselect 2k items to select the needed ones is a huge effort.

 Would you have any clue where to look at this (I am not afraid of getting my hands dirty)?

Thank you!

**Comment by bheisig** [comment]
Hi,

Thanks for your report. I can confirm this is a reproducible bug. Fortunately, it has been fixed since commit 0c5dee0cc623b3b52419f3b25156c6146c38f223. All you have to do is to install/update this extension from source as described in the [README.md](README.md).

Please let me know whether this fixes your problem. Then, I'll push a new release to CPAN.

– Ben

**Comment by rmoliveira-etux** [comment]
Ben,
 Perfect, thank you very much, it is fixed now.
 Would you be interested in some feature request ideas?
Thank you,
